export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

import { NextResponse } from 'next/server';
import crypto from 'crypto';
import { supabase } from '../../../../utils/supabase';

/**
 * POST /api/checkout/razorpay/verify
 * Cryptographic Signature Verification:
 * Validates HMAC SHA-256 signature generated by Razorpay
 * Prevents client-side payment spoofing and unauthorized order status elevation.
 */
export async function POST(req) {
    try {
        const body = await req.json();
        const {
            razorpay_order_id,
            razorpay_payment_id,
            razorpay_signature,
            orderNumber
        } = body;

        if (!razorpay_order_id || !razorpay_payment_id || !razorpay_signature) {
            return NextResponse.json(
                { verified: false, error: 'Missing payment signature verification parameters.' },
                { status: 400 }
            );
        }

        // Fetch Razorpay secret key securely from admin_settings
        const { data: settings, error: settingsError } = await supabase
            .from('admin_settings')
            .select('razorpayKeySecret')
            .single();

        if (settingsError || !settings?.razorpayKeySecret) {
            return NextResponse.json(
                { verified: false, error: 'Razorpay secret key not configured in store settings.' },
                { status: 500 }
            );
        }

        // Compute HMAC SHA256 signature
        const expectedSignature = crypto
            .createHmac('sha256', settings.razorpayKeySecret)
            .update(`${razorpay_order_id}|${razorpay_payment_id}`)
            .digest('hex');

        // Timing-safe comparison to prevent timing-attack vulnerability
        const expectedBuffer = Buffer.from(expectedSignature, 'utf8');
        const actualBuffer = Buffer.from(razorpay_signature, 'utf8');

        if (expectedBuffer.length !== actualBuffer.length || !crypto.timingSafeEqual(expectedBuffer, actualBuffer)) {
            console.error(`[SECURITY ALERT] Invalid Razorpay signature for order ${orderNumber || 'unknown'}`);
            return NextResponse.json(
                { verified: false, error: 'Cryptographic signature mismatch. Payment verification failed.' },
                { status: 400 }
            );
        }

        return NextResponse.json({
            verified: true,
            order_id: razorpay_order_id,
            payment_id: razorpay_payment_id,
            status: 'Paid'
        }, { status: 200 });

    } catch (error) {
        console.error('Razorpay Verification Error:', error);
        return NextResponse.json(
            { verified: false, error: error.message || 'Internal payment verification error' },
            { status: 500 }
        );
    }
}
